pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Install Dependencies') {
      steps {
        dir('app/Angular-10-Spring-Boot-CRUD-Full-Stack-App-master/angular-frontend') {
          sh 'npm install'
        }
      }
    }

    stage('Run Tests') {
      steps {
        dir('app/Angular-10-Spring-Boot-CRUD-Full-Stack-App-master/angular-frontend') {
          sh 'export NODE_OPTIONS=--openssl-legacy-provider && npm test --watch=false'
        }
      }
    }

    stage('Deploy') {
      steps {
        echo 'Deployment folgt später – z. B. auf Webserver kopieren oder Container starten.'
      }
    }
  }

  post {
    always {
      echo 'Pipeline abgeschlossen.'
    }
  }
}
