pipeline {
  agent any

  environment {
    NODE_OPTIONS = "--max_old_space_size=4096"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Install Dependencies') {
      steps {
        dir('app/Angular-10-Spring-Boot-CRUD-Full-Stack-App-master/angular-frontend') {
          sh 'npm install'
        }
      }
    }

    stage('Run Tests') {
      steps {
        dir('app/Angular-10-Spring-Boot-CRUD-Full-Stack-App-master/angular-frontend') {
          sh 'npm test --watch=false'
        }
      }
    }

    stage('Deploy') {
      steps {
        echo 'Frontend-Deployment folgt später.'
      }
    }
  }

  post {
    always {
      echo 'Pipeline abgeschlossen.'
    }
  }
}
