name: Build & Test Java Backend

on:
  push:
    paths:
      - 'Angular-10-Spring-Boot-CRUD-Full-Stack-App-master/springboot-backend/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        working-directory: Angular-10-Spring-Boot-CRUD-Full-Stack-App-master/springboot-backend
        run: mvn clean install

      - name: Run tests
        working-directory: Angular-10-Spring-Boot-CRUD-Full-Stack-App-master/springboot-backend
        run: mvn test
